/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo_da_velha;

/**
 *
 * @author cassi
 */
public class Tela_Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Jogo
     */
    Arvore arvore;
    
    public Tela_Jogo(Arvore arvore) {
        this.arvore = arvore;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0))
        );
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1))
        );
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2))
        );
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3))
        );
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4))
        );
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5))
        );
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6))
        );
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7))
        );
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8))
        );
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setText("Jogo da Velha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(" ".equals(jButton1.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
           // arvore.zerarProx();
          //  arvore.getRaiz().setJogada(0);
            //arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 0);
            if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(0));
            arvore.procuraJogada(0);
             jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
             if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
             if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
          //       arvore.expandindoArvore();
            //     arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
             if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(" ".equals(jButton2.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
            //arvore.zerarProx();
            //arvore.getRaiz().setJogada(0);
           // arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 1);
            if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(1));
           arvore.procuraJogada(1); 
           jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
            //     arvore.expandindoArvore();
              //   arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(" ".equals(jButton3.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
           // arvore.zerarProx();
           // arvore.getRaiz().setJogada(0);
            //arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 2);
                        if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(2));
            arvore.procuraJogada(2);
            jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
           //      arvore.expandindoArvore();
             //    arvore.explorarArvore(arvore.getRaiz());
                 //System.out.println(arvore.getRaiz().getTabuleiro().getPosicao(0)+" "+arvore.getRaiz().getTabuleiro().getPosicao(1)+" "+arvore.getRaiz().getTabuleiro().getPosicao(2)+"\n"+arvore.getRaiz().getTabuleiro().getPosicao(3)+" "+arvore.getRaiz().getTabuleiro().getPosicao(4)+" "+arvore.getRaiz().getTabuleiro().getPosicao(5)+"\n"+arvore.getRaiz().getTabuleiro().getPosicao(6)+" "+arvore.getRaiz().getTabuleiro().getPosicao(7)+" "+arvore.getRaiz().getTabuleiro().getPosicao(8)+"\n");
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(" ".equals(jButton4.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
            //arvore.zerarProx();
            //arvore.getRaiz().setJogada(0);
            //arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 3);
                        if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(3));
            arvore.procuraJogada(3);
            jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
              //   arvore.expandindoArvore();
               //  arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(" ".equals(jButton5.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
            //arvore.zerarProx();
            //arvore.getRaiz().setJogada(0);
            //arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 4);
                        if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(4));
            arvore.procuraJogada(4);
            jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
               //  arvore.expandindoArvore();
               //  arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(" ".equals(jButton6.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
            //arvore.zerarProx();
            //arvore.getRaiz().setJogada(0);
            //arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 5);
                        if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(5));
            arvore.procuraJogada(5);
            jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
              //   arvore.expandindoArvore();
                // arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(" ".equals(jButton7.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
           // arvore.zerarProx();
            //arvore.getRaiz().setJogada(0);
           // arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 6);
                       if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(6));
           arvore.procuraJogada(6); 
           jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 //arvore.expandindoArvore();
                // arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 // arvore.expandindoArvore();
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(" ".equals(jButton8.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
            //arvore.zerarProx();
            //arvore.getRaiz().setJogada(0);
            //arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(),7);
                        if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(7));
            arvore.procuraJogada(7);
            jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
              //   arvore.expandindoArvore();
               //  arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(" ".equals(jButton9.getText()) && !arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) && !arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro())){
            //arvore.zerarProx();
            //arvore.getRaiz().setJogada(0);
            //arvore.getRaiz().getTabuleiro().setPosicao(arvore.getPlayer(), 8);
                        if(arvore.tabVazio(arvore.getRaiz().getTabuleiro()))
                arvore.explorarArvore(arvore.getRaiz().getProx(8));
            arvore.procuraJogada(8);
            jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
                 return;
             }
            if(!arvore.fimdejogo(arvore.getPlayer(), arvore.getRaiz().getTabuleiro()) && !arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
              //   arvore.expandindoArvore();
                // arvore.explorarArvore(arvore.getRaiz());
                 arvore.novaRaiz(arvore.getRaiz());
                 jButton1.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(0)));
                 jButton2.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(1)));
                 jButton3.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(2)));
                 jButton4.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(3)));
                 jButton5.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(4)));
                 jButton6.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(5)));
                 jButton7.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(6)));
                 jButton8.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(7)));
                 jButton9.setText(String.valueOf(arvore.getRaiz().getTabuleiro().getPosicao(8)));
             }
            if(arvore.fimdejogo('X', arvore.getRaiz().getTabuleiro()) || arvore.fimdejogo('O', arvore.getRaiz().getTabuleiro()) || arvore.tabCheio(arvore.getRaiz().getTabuleiro())){
                 Tela_Fim tf = new Tela_Fim(arvore);
                 tf.setVisible(true);
                 dispose();
             }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
